// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rderManagementApi.Model;

#nullable disable

namespace OrderManagementApi.Migrations
{
    [DbContext(typeof(DbOrderManagementContext))]
    [Migration("20230530191459_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementApi.Model.OrderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customerAddress");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customerName");

                    b.Property<int>("Discount")
                        .HasMaxLength(200)
                        .HasColumnType("int")
                        .HasColumnName("discount");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("itemName");

                    b.Property<DateTime>("OrderDateTime")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2")
                        .HasColumnName("orderDateTime");

                    b.Property<string>("OrderInvoiceNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("orderInvoiceNo");

                    b.Property<int>("Quantity")
                        .HasMaxLength(200)
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("shippingAddress");

                    b.Property<DateTime>("ShippingDate")
                        .HasMaxLength(200)
                        .HasColumnType("datetime2")
                        .HasColumnName("shippingDate");

                    b.Property<decimal>("TotalPrice")
                        .HasMaxLength(250)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("totalPrice");

                    b.Property<decimal>("UnitPrice")
                        .HasMaxLength(250)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unitPrice");

                    b.HasKey("Id");

                    b.ToTable("OrderInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
